# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/fluxion.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(804, 527)
        MainWindow.setAnimated(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.BottomTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.BottomTabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.BottomTabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.BottomTabWidget.setObjectName(_fromUtf8("BottomTabWidget"))
        self.LogTab = QtGui.QWidget()
        self.LogTab.setObjectName(_fromUtf8("LogTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.LogTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.ProcessesTableView = QtGui.QTableView(self.LogTab)
        self.ProcessesTableView.setObjectName(_fromUtf8("ProcessesTableView"))
        self.gridLayout_3.addWidget(self.ProcessesTableView, 0, 0, 1, 1)
        self.BottomTabWidget.addTab(self.LogTab, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.BottomTabWidget, 1, 0, 1, 1)
        self.MainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.MainTabWidget.setObjectName(_fromUtf8("MainTabWidget"))
        self.ScanTab = QtGui.QWidget()
        self.ScanTab.setObjectName(_fromUtf8("ScanTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.ScanTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter = QtGui.QSplitter(self.ScanTab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.HostsTabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HostsTabWidget.sizePolicy().hasHeightForWidth())
        self.HostsTabWidget.setSizePolicy(sizePolicy)
        self.HostsTabWidget.setObjectName(_fromUtf8("HostsTabWidget"))
        self.HostsTab = QtGui.QWidget()
        self.HostsTab.setObjectName(_fromUtf8("HostsTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.HostsTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.HostsTableView = QtGui.QTableView(self.HostsTab)
        self.HostsTableView.setObjectName(_fromUtf8("HostsTableView"))
        self.gridLayout_5.addWidget(self.HostsTableView, 0, 0, 1, 1)
        self.HostsTabWidget.addTab(self.HostsTab, _fromUtf8(""))
        self.ServicesLeftTab = QtGui.QWidget()
        self.ServicesLeftTab.setObjectName(_fromUtf8("ServicesLeftTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.ServicesLeftTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.ServiceNamesTableView = QtGui.QTableView(self.ServicesLeftTab)
        self.ServiceNamesTableView.setObjectName(_fromUtf8("ServiceNamesTableView"))
        self.gridLayout_6.addWidget(self.ServiceNamesTableView, 0, 0, 1, 1)
        self.HostsTabWidget.addTab(self.ServicesLeftTab, _fromUtf8(""))
        self.ServicesTabWidget = QtGui.QTabWidget(self.splitter)
        self.ServicesTabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ServicesTabWidget.sizePolicy().hasHeightForWidth())
        self.ServicesTabWidget.setSizePolicy(sizePolicy)
        self.ServicesTabWidget.setObjectName(_fromUtf8("ServicesTabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.lineEdit = QtGui.QLineEdit(self.tab_3)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 113, 30))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 62, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.ServicesTabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.ServicesRightTab = QtGui.QWidget()
        self.ServicesRightTab.setObjectName(_fromUtf8("ServicesRightTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.ServicesRightTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ServicesTableView = QtGui.QTableView(self.ServicesRightTab)
        self.ServicesTableView.setObjectName(_fromUtf8("ServicesTableView"))
        self.verticalLayout.addWidget(self.ServicesTableView)
        self.ServicesTabWidget.addTab(self.ServicesRightTab, _fromUtf8(""))
        self.InformationTab = QtGui.QWidget()
        self.InformationTab.setObjectName(_fromUtf8("InformationTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.InformationTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.InformationTableView = QtGui.QTableView(self.InformationTab)
        self.InformationTableView.setObjectName(_fromUtf8("InformationTableView"))
        self.gridLayout_2.addWidget(self.InformationTableView, 0, 0, 1, 1)
        self.ServicesTabWidget.addTab(self.InformationTab, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.MainTabWidget.addTab(self.ScanTab, _fromUtf8(""))
        self.HandshakeTab = QtGui.QWidget()
        self.HandshakeTab.setObjectName(_fromUtf8("HandshakeTab"))
        self.BruteTabWidget = QtGui.QTabWidget(self.HandshakeTab)
        self.BruteTabWidget.setGeometry(QtCore.QRect(9, 9, 391, 171))
        self.BruteTabWidget.setObjectName(_fromUtf8("BruteTabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 30, 191, 30))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 62, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 100, 90, 28))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.radioButton = QtGui.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(0, 70, 109, 25))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(0, 90, 109, 25))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.BruteTabWidget.addTab(self.tab, _fromUtf8(""))
        self.MainTabWidget.addTab(self.HandshakeTab, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.MainTabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.BottomTabWidget.setCurrentIndex(0)
        self.MainTabWidget.setCurrentIndex(0)
        self.HostsTabWidget.setCurrentIndex(1)
        self.ServicesTabWidget.setCurrentIndex(0)
        self.BruteTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.BottomTabWidget.setTabText(self.BottomTabWidget.indexOf(self.LogTab), _translate("MainWindow", "Log", None))
        self.HostsTabWidget.setTabText(self.HostsTabWidget.indexOf(self.HostsTab), _translate("MainWindow", "Hosts", None))
        self.HostsTabWidget.setTabText(self.HostsTabWidget.indexOf(self.ServicesLeftTab), _translate("MainWindow", "Services", None))
        self.label.setText(_translate("MainWindow", "IP Range", None))
        self.ServicesTabWidget.setTabText(self.ServicesTabWidget.indexOf(self.tab_3), _translate("MainWindow", "Scope", None))
        self.ServicesTabWidget.setTabText(self.ServicesTabWidget.indexOf(self.ServicesRightTab), _translate("MainWindow", "Services", None))
        self.ServicesTabWidget.setTabText(self.ServicesTabWidget.indexOf(self.InformationTab), _translate("MainWindow", "Information", None))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.ScanTab), _translate("MainWindow", "Scan", None))
        self.label_2.setText(_translate("MainWindow", "Path", None))
        self.pushButton_2.setText(_translate("MainWindow", "Start", None))
        self.radioButton.setText(_translate("MainWindow", "Aircrack", None))
        self.radioButton_2.setText(_translate("MainWindow", "Pyrit", None))
        self.BruteTabWidget.setTabText(self.BruteTabWidget.indexOf(self.tab), _translate("MainWindow", "Analyzer", None))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.HandshakeTab), _translate("MainWindow", "Handshake", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

